import localFont from "next/font/local";
import "./globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faBitcoin,
  faCircle,
  faCircleCheck,
  faCoins,
  faDiamond,
  faGamepad,
  faHome,
  faLitecoinSign,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import Nave from "./component/Nave";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" flex items-center justify-center  bg-no-repeat bg-cover bg-center md:w-[400px] overflow-hidden bg-gray-900 mx-auto">
          <div className="container mx-auto  h-screen relative">
            <h1 className="text-sm uppercase text-center bg-gray-400 text-gray-50">shamim</h1>
            {children}
            <Nave />
          </div>
        </div>
      </body>
    </html>
  );
}
